### ISSUE TITLE
Missing pkl file to run chunkify 

### ISSUE THREAD

**Issue by tungufoss** [nanoporetech/sloika#1]
The `sloika/models/retrained.pkl` file referred in line 25 [scripts/example_training.sh](https://github.com/nanoporetech/sloika/blob/5874bbdf47b94006e87dc746d7d79570c42b0b98/scripts/example_training.sh) is missing from the repository. And I assume `model/baseline.pkl` in line 31 is should be the same input file? 
I tried the `baseline.pkl` file I used in the earlier release of sloika, but it raised the error _Model file {} was neither a network nor compiled network_. Same error occurs using the currently only included pkl file, [`models/pretrained.pkl`](https://github.com/nanoporetech/sloika/blob/5874bbdf47b94006e87dc746d7d79570c42b0b98/models/pretrained.pkl).

**Comment by tmassingham-ont** [comment]
Thanks.  I've corrected path to model files and made a few small clean-ups to the example script but I'm unable to replicated the error when you get when using `models/pretrained.pkl`

**Comment by tungufoss** [comment]
The problem was a missing library that had been mysteriously uninstalled. The `models/pretrained.pkl` works 👍
