### ISSUE TITLE
error installing on ubuntu

### ISSUE THREAD

**Issue by michieitel** [nanoporetech/sloika#2]
Hi!

I am trying to install sloika on an Ubuntu distribution but when it comes to the setup.py it throws an error:

> error in sloika setup command: "values of 'package_data' dict" must be a list of strings (got 'data/configs/*')

Looking into the "data" folder I cannot find the "config" folder that is expected. I tried using both cloning via git and installing from source. How can I get that folder? Should it be generated during the initial steps?

Thanks
Michael

**Comment by vineeth-s** [comment]
Hi @michieitel,
Not directly an answer to your question but imo sloika is not really the way to go anymore for training models 
We have been using [https://github.com/nanoporetech/taiyaki](Taiyaki)

**Comment by michieitel** [comment]
Thanks for you reply. This means I just have to figure out how to install another tool.... Oh man this field is moving forward so fast I can't keep up ;-)

cheers
M
